server.document-root = "/usr/share/webapps/cgit"
server.port = 80
server.username = "lighttpd"
server.groupname = "lighttpd"

index-file.names = ( "cgit.cgi" )

cgi.assign = ( ".cgi" => "" )

static-file.exclude-extensions = ( ".cgi" )

server.modules += ( "mod_cgi", "mod_rewrite" )

$HTTP["url"] !~ "\.(css|js|png|ico|gif|svg|txt)$" {
    url.rewrite-once = ( "^/(.*)$" => "/cgit.cgi/$1" )
}
